version: '3.8'

services:
  # rabbitmq:
  #   image: rabbitmq:3.8-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
  #   networks:
  #     - dummy_ecs

  microservice_a:
    build: ./microA
    ports:
      - "8000:8000"
    # depends_on:
    #   - rabbitmq
    restart: "on-failure"
    networks:
      - dummy_ecs

  microservice_b:
    build: ./microB
    ports:
      - "8001:8001"
    # depends_on:
    #   - rabbitmq
    restart: "on-failure"
    networks:
      - dummy_ecs

  microservice_c:
    build: ./microC
    ports:
      - "8002:8002"
    # depends_on:
    #   - rabbitmq
    restart: "on-failure"
    networks:
      - dummy_ecs

networks:
  dummy_ecs:
    external: true
